FROM golang:latest AS builder

WORKDIR /build

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o httpout ./cmd/httpserver/main.go

EXPOSE 8080

FROM scratch
WORKDIR /app
COPY --from=builder /build/httpout .

ENTRYPOINT [ "/app/httpout" ]
