apiVersion: v1
kind: Service
metadata:
  name: gin-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.ginAppName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 30500